version: 2
plugins:
    eslint:
        enabled: true
        channel: "eslint-5"
    coffeelint:
        enabled: true
        config: coffeelint.json
    fixme:
        enabled: true
    tailor:
        enabled: true
    shellcheck:
        enabled: true
    duplication:
        enabled: false

