engines:
    coffeelint:
        enabled: true
        config: coffeelint.json
    fixme:
        enabled: true
    tailor:
        enabled: true
    shellcheck:
        enabled: true
ratings:
    paths:
        - "**"
