language: node_js
node_js:
  - "4.1"
  - "0.11"
  - "stable"
before_script:
  - PATH=`echo $PATH | sed -e 's/:\.\/node_modules\/\.bin//g'` find ./node_modules/neft-* -maxdepth 0 -type d -exec sh -c 'cd $0; npm install --only=prod' {} \;
  - rm -rf ./node_modules/neft-*/node_modules/neft-*
  - npm run bundle -- --node --browser
