os:
  - linux
  - osx
language: node_js
node_js:
  - "0.11"
  - "5.11"
  - "6.2"
before_script:
  - npm run bundle -- --node --browser
script:
  - npm test -- --coverage
after_script:
  - node_modules/.bin/istanbul report
  - node_modules/.bin/coveralls < coverage/lcov.info
