notifications:
    email: false
sudo: false
language: node_js
# addons:
#     apt:
#         sources:
#             - google-chrome
#         packages:
#             - google-chrome-stable
cache:
    apt: true
    directories:
        - node_modules
before_script:
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\""
    - nvm install 0.11.0
    - nvm install 4.1.2
    - nvm install 5.0.0
    - nvm install 6.2.2
    - nvm install 7.0.0
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm run bundle -- --node --browser --ios --android
script:
    - npm test
env:
    global:
        - TEST_NVM=1
        - TEST_CHROME=1
matrix:
    include:
        # -
        #     language: android
        #     os: linux
        #     env:
        #         - JOB_TYPE="android"
        #         - TRAVIS_NODE_VERSION=5.11
        #         - NEFT_TEST_ANDROID=1
        #     install:
        #         - nvm install $TRAVIS_NODE_VERSION
        #         - npm install
        #     android:
        #         components:
        #             - build-tools-23.0.0
        #             - android-23
        #             - extra
        # -
        #     os: osx
        #     node_js: "5.11"
        #     osx_image: xcode8.1sneakpeek # https://github.com/travis-ci/travis-ci/issues/6791#issuecomment-260052295
        #     env:
        #         - JOB_TYPE="ios"
        #         - NEFT_TEST_IOS=1
        #         - NEFT_IOS_VERSION=10.1
        #     install:
        #         - xcodebuild -showsdks
        #         - npm install
        -
            os: linux
            node_js: "6.2"
