language: node_js
node_js:
  - "4.1"
  - "0.11"
  - "stable"
before_script:
  - ./node_modules/force-dedupe-git-modules/bin/force-dedupe-git-modules
script:
  - npm test -- --require coffee-coverage/register-istanbul
after_script:
  - istanbul report
  - coveralls < coverage/lcov.info
