os: Visual Studio 2015
version: '{build}-{branch}'
platform: x64
build: off
environment:
    nodejs_version: "10.15.3"
install:
    - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) x64
    - npm install
    - npx lerna bootstrap
test_script:
    - node --version
    - npm --version
    - npm test
