references:
    workspace_root: &workspace_root
        ~/neft
    node_dependencies_cache_key: &node_dependencies_cache_key "\
        node-dependency-cache-\
        {{ checksum \"package-lock.json\" }}"
    attach_workspace: &attach_workspace
        attach_workspace:
            at: *workspace_root
    run_tests: &run_tests
        run: npm test

defaults: &defaults
    working_directory: *workspace_root
    docker:
        - image: circleci/node:10.15.3

version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                key: *node_dependencies_cache_key
            - run: npm install
            - run: npx lerna bootstrap
            - save_cache:
                key: *node_dependencies_cache_key
                paths:
                    - node_modules
            - persist_to_workspace:
                root: *workspace_root
                paths:
                    - .
    test_linux_node:
        <<: *defaults
        steps:
            - *attach_workspace
            - *run_tests
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test_linux_node:
                requires:
                    - build
